### ISSUE TITLE
question

### ISSUE THREAD

**Issue by suave123** [hmmbob/HomeAssistantConfig#3]
Hi Bob,

Ik zag je issues met de apex chart. Ik heb zelf ook een probleem met die charts. bij mij zijn ze sinds 2 maanden leeg, de x en y as is wel zichtbaar maar er komt geen grafiek meer in. Enig idee hoe dat op te lossen?

<img width="1102" alt="Scherm­afbeelding 2023-04-12 om 12 48 11" src="https://user-images.githubusercontent.com/35298826/231435583-4fb836e8-3551-4ed8-a4d4-f65bf67e4c67.png">

**Comment by hmmbob** [comment]
Sorry, zie nu pas je issue. Is dit al opgelost?

**Comment by suave123** [comment]
NeeVerstuurd vanaf mijn iPhoneOp 25 apr. 2023 om 11:06 heeft Hmmbob ***@***.***> het volgende geschreven:﻿
Sorry, zie nu pas je issue. Is dit al opgelost?

**Comment by hmmbob** [comment]
Is je ApexCharts up to date?

En anders verwacht ik een issue in de `data_generator` sectie.

**Comment by suave123** [comment]
Ja is uptodate, grafieken vullen niet meer maar de losse data update welVerstuurd vanaf mijn iPhoneOp 25 apr. 2023 om 11:55 heeft Hmmbob ***@***.***> het volgende geschreven:﻿
Is je ApexCharts up to date?
En anders verwacht ik een issue in de data_generator sectie.

**Comment by hmmbob** [comment]
MIsschien even op Tweakers of het HA forum delen, dan kunnen er meer mensen meekijken?
