### ISSUE TITLE
Missing scripts  for "Push sensor vales to luftdaten"

### ISSUE THREAD

**Issue by NeverUsedID** [hmmbob/HomeAssistantConfig#4]
Hi, came here from https://community.home-assistant.io/t/push-sensor-vales-to-luftdaten/209295/7  to get the scripts to send my data to sensor.community, but all the links a dead. Where can i find your scripts?

**Comment by NeverUsedID** [comment]
Foudn it: https://github.com/hmmbob/HomeAssistantConfig/blob/master/packages/0%20-%20Ground%20floor/Outside/air_quality.yaml

**Comment by hmmbob** [comment]
Jupz, that's the one.

And now let me investigate why I didn't get a ping for this issue, I kinda discovered it by accident.....
